export type Metric = { value: string; label: string; context: string };
export type Section = { title: string; body: string };

export type WorkItem = {
  slug: string;
  title: string;
  category: "Marketing" | "Games & Interactive" | "3D & Motion" | "Visual Art";
  depth: "case" | "compact";
  role: string;
  summary: string;
  heroMedia: string;
  accent: string;
  tools: string[];
  metrics?: Metric[];
  sections?: Section[];
  gallery: string[];
  externalLinks?: { label: string; href: string }[];
};

export const work: WorkItem[] = [
  {
    slug: "echos-of-her",
    title: "Echos of Her",
    category: "Games & Interactive",
    depth: "case",
    role: "Creative Director · Game Designer · Visual Development",
    summary: "An interactive memory experience that transforms a deeply personal story into a public-facing cultural installation.",
    heroMedia: "/media/echos-poster.webp",
    accent: "#b88a72",
    tools: ["Unity", "Blender", "Adobe Creative Suite", "Narrative Design"],
    metrics: [
      { value: "10", label: "Cities", context: "Presented across a national touring programme in China." },
      { value: "170 × 18 m", label: "Media façade", context: "The work appeared on a landmark public screen in Hangzhou." },
      { value: "400+", label: "Submissions", context: "Selected from more than four hundred entries." },
      { value: "2025", label: "Gold Prize", context: "Gold Prize and Tuzishan finalist recognition." },
    ],
    sections: [
      { title: "Overview", body: "Echos of Her is a narrative-led interactive work about memory, absence and the traces people leave behind. I shaped its visual system, interaction language and public presentation so an intimate story could remain legible at exhibition scale." },
      { title: "Challenge", body: "The experience needed to feel emotionally specific without relying on exposition. It also had to move between a playable screen, award presentation and an enormous urban media façade while preserving a coherent identity." },
      { title: "My Role", body: "I led creative direction, game design, visual development and presentation strategy—connecting the emotional premise to interaction, art direction and the audience journey." },
      { title: "Process", body: "The process moved from memory fragments and visual motifs into interaction prototypes, cinematic compositions and a modular presentation system. Repeated playtests focused on pacing, comprehension and emotional rhythm." },
      { title: "Outcome", body: "The project won a 2025 Gold Prize, became a Tuzishan finalist and toured ten cities. Its strongest outcome was proving that a personal interactive story could travel across radically different formats without losing its emotional centre." },
    ],
    gallery: ["/media/echos-award.webp", "/media/echos-art-1.webp", "/media/echos-art-2.webp", "/media/echos-screen.webp"],
  },
  {
    slug: "meat-lover",
    title: "Meat Lover",
    category: "Marketing",
    depth: "case",
    role: "Creative Marketing · Content Strategy · Game Design",
    summary: "A deliberately strange cutting-game concept turned into a fast, measurable social launch through positioning, content design and community feedback.",
    heroMedia: "/media/meat-hero.webp",
    accent: "#ff623f",
    tools: ["Unity", "RedNote", "Content Strategy", "Analytics"],
    metrics: [
      { value: "70K+", label: "Views", context: "Debut post reach on RedNote." },
      { value: "1.6K+", label: "Likes", context: "Organic response to the initial launch creative." },
      { value: "~2K", label: "Engagements", context: "Combined interactions generated by the debut post." },
      { value: "22.4%", label: "Conversion", context: "39 link clicks from 174 tracked landing-page views." },
    ],
    sections: [
      { title: "Overview", body: "Meat Lover pairs tactile cutting interactions with an absurd, memorable premise. The marketing strategy treated the game’s strangeness as an advantage and built a recognisable voice around quick visual payoffs." },
      { title: "Challenge", body: "With no established audience, the launch needed to communicate the mechanic instantly, earn attention in-feed and convert curiosity into meaningful actions rather than vanity reach." },
      { title: "My Role", body: "I worked across game concept, creative positioning, asset production, post design and performance review. Product decisions and marketing decisions were developed together." },
      { title: "Process", body: "I isolated the most visually satisfying moments, tested concise hooks, built a repeatable content identity and used early audience behaviour to refine the message and call to action." },
      { title: "Outcome", body: "The launch reached more than 70,000 views and 1,600 likes, with almost 2,000 engagements. The project gained roughly 500 followers in three days and recorded a 22.4% tracked conversion rate." },
    ],
    gallery: ["/media/meat-identity.webp", "/media/meat-ui.webp", "/media/meat-social.webp"],
  },
  {
    slug: "soul-vein",
    title: "Soul Vein",
    category: "Games & Interactive",
    depth: "case",
    role: "Game Design · Level Design · Programming · Narrative",
    summary: "A systems-driven student game in which level structure, mechanics and story are designed as one connected player journey.",
    heroMedia: "/media/soul-hero.webp",
    accent: "#6ec5b7",
    tools: ["Unity", "C#", "Level Design", "Narrative Design"],
    sections: [
      { title: "Overview", body: "Soul Vein explores how environmental progression can carry both mechanical stakes and narrative meaning. The project was built as a connected design problem rather than a collection of isolated features." },
      { title: "Challenge", body: "The core challenge was balancing readable progression with an atmosphere of uncertainty, while keeping the level, code and narrative flexible enough to evolve together." },
      { title: "My Role", body: "I contributed game design, level design, programming and narrative work, taking ideas from paper logic into playable sequences and iteration." },
      { title: "Process", body: "I mapped player beats, built greybox spaces, implemented interaction logic and revised pacing through repeated playtests. Narrative cues were placed where player attention naturally slowed." },
      { title: "Outcome", body: "The final prototype demonstrates a coherent player journey in which space, system and story reinforce one another—and reflects my ability to work across creative and technical boundaries." },
    ],
    gallery: ["/media/soul-level.webp", "/media/soul-gameplay.webp", "/media/soul-code.webp"],
  },
  { slug: "personal-rednote", title: "Personal RedNote", category: "Marketing", depth: "compact", role: "Content Strategy · Social Creative", summary: "An ongoing personal channel used to test hooks, visual formats and audience behaviour through direct publishing.", heroMedia: "/media/rednote.webp", accent: "#f45b68", tools: ["RedNote", "Content Production", "Analytics"], gallery: ["/media/rednote.webp"] },
  { slug: "commercial-games", title: "Commercial Game Experience", category: "Marketing", depth: "compact", role: "QA · Asset Integration · Marketing", summary: "Cross-functional experience supporting commercial game teams, from marketing research to QA and production-ready asset integration.", heroMedia: "/media/commercial.webp", accent: "#a7a6ff", tools: ["Unity", "QA", "Asset Integration", "Research"], gallery: ["/media/commercial.webp", "/media/rollercoaster.webp"] },
  { slug: "reapers-roulette", title: "Reaper’s Roulette", category: "Games & Interactive", depth: "compact", role: "Game Design · Development", summary: "A high-pressure interactive concept built around risk, timing and readable player choices.", heroMedia: "/media/reapers.webp", accent: "#a14135", tools: ["Unity", "C#", "Game Design"], gallery: ["/media/reapers.webp"] },
  { slug: "untitled-capybara", title: "Untitled Capybara Game", category: "Games & Interactive", depth: "compact", role: "Game Design · Art", summary: "A playful capybara-led prototype focused on charm, accessible interaction and rapid iteration.", heroMedia: "/media/capybara.webp", accent: "#d7a66d", tools: ["Unity", "Prototyping", "2D Art"], gallery: ["/media/capybara.webp"] },
  { slug: "pengci-grandma", title: "PengCi Grandma", category: "Games & Interactive", depth: "compact", role: "Game Design · Visual Design", summary: "A humorous interactive project translating a culturally specific idea into an immediately readable mechanic.", heroMedia: "/media/grandma.webp", accent: "#e6d23f", tools: ["Unity", "Game Design", "Visual Design"], gallery: ["/media/grandma.webp"] },
  { slug: "shauns-last-escape", title: "Shaun’s Last Escape", category: "Games & Interactive", depth: "compact", role: "Game Design · Development", summary: "A compact escape experience that uses environment, pressure and pacing to guide the player.", heroMedia: "/media/shaun.webp", accent: "#dd765a", tools: ["Unity", "C#", "Level Design"], gallery: ["/media/shaun.webp"] },
  { slug: "3d-modeling", title: "3D Modeling", category: "3D & Motion", depth: "compact", role: "3D Artist", summary: "Hard-surface modeling studies focused on silhouette, material readability and presentation.", heroMedia: "/media/car.webp", accent: "#6b8a9d", tools: ["Maya", "Substance 3D", "Rendering"], gallery: ["/media/car.webp"] },
  { slug: "weapon-animation", title: "Weapon Animation", category: "3D & Motion", depth: "compact", role: "Animator", summary: "Animation studies exploring weight, anticipation and responsive first-person motion.", heroMedia: "/media/weapon.webp", accent: "#7798ad", tools: ["Maya", "Animation", "Unity"], gallery: ["/media/weapon.webp"] },
  { slug: "motion-capture", title: "Motion Capture", category: "3D & Motion", depth: "compact", role: "Performer · Motion Editor", summary: "A movement study spanning performance capture, cleanup and application in a real-time pipeline.", heroMedia: "/media/mocap.webp", accent: "#7bc8c8", tools: ["Motion Capture", "Maya", "Unity"], gallery: ["/media/mocap.webp"] },
  { slug: "bridget", title: "Bridget", category: "Visual Art", depth: "compact", role: "Character Designer", summary: "A character design study developed through silhouette, costume language and expressive detail.", heroMedia: "/media/bridget.webp", accent: "#dc6d83", tools: ["Procreate", "Character Design", "Illustration"], gallery: ["/media/bridget.webp"] },
  { slug: "allergy", title: "Allergy", category: "Visual Art", depth: "compact", role: "Visual Artist", summary: "A graphic narrative experiment using composition and metaphor to make an internal sensation visible.", heroMedia: "/media/allergy.webp", accent: "#9d7fa7", tools: ["Illustration", "Visual Narrative", "Adobe Creative Suite"], gallery: ["/media/allergy.webp"] },
  { slug: "painting", title: "Painting", category: "Visual Art", depth: "compact", role: "Painter", summary: "Selected observational and expressive works exploring colour, atmosphere and visual memory.", heroMedia: "/media/painting-1.webp", accent: "#b67e5d", tools: ["Traditional Media", "Digital Painting", "Composition"], gallery: ["/media/painting-1.webp", "/media/painting-2.webp", "/media/painting-3.webp"] },
];

export const featured = work.filter((item) => ["echos-of-her", "meat-lover", "soul-vein"].includes(item.slug));
export const categories = ["All", "Marketing", "Games & Interactive", "3D & Motion", "Visual Art"] as const;

export function getWork(slug: string) {
  return work.find((item) => item.slug === slug);
}
